### ISSUE TITLE
Input data columns

### ISSUE THREAD

**Issue by Jade0904** [DavisLaboratory/scDECAF#4]
Hello, I have a question regarding the input data. As mentioned in the help document, the input "data" for scDECAF() is a numeric matrix where rows are genes and columns are cells or samples. I would like to ask, typically, what kind of columns would you like to suggest to use when applying scDECAF? Do you suggest to use different cells, or biologically repeated samples, or the same cells / samples but at different time points? It would be highly appreciated if you could give me some simple examples. Thanks a lot :)

**Comment by soroorh** [comment]
Hey - thank you for using the issue tracker.

The input matrix could be genes x single cells under any of the settings you mentioned i.e. the model is not making any assumptions about presence of biological replicates etc.

For example workflows, i suggest you check notebooks listed in #2 
Hope this helps!
